version: '3.8'

services:
  app:
    build: 
      context: ./portfolio-front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
